### ISSUE TITLE
Could not autoload puppet/type/ufw_rule: no such file to load -- puppet/resource_api

### ISSUE THREAD

**Issue by dwest-galois** [kogitoapp/puppet-ufw#9]
I started using this module to manage UFW, but I seem to be running into an issue on some, but not all, of my Ubuntu systems.

`
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/ufw_rule: no such file to load -- puppet/resource_api (file: /etc/puppetlabs/code/environments/development/modules/ufw/manifests/init.pp, line: 164, column: 5) on node servername.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
`
It does not seem to be specific to any particular version of Ubuntu, but the most common one I see it happening on is 20.04.4 LTS.  Here are some of the details:

OS Versions: Ubuntu 20.04.4 LTS, Ubuntu 18.04.6 LTS
Puppet Version: 7.17.0
Puppet Modules (related):
 - mod 'kogitoapp-ufw', '1.0.3'
 - mod 'puppetlabs-puppetserver_gem', '1.1.1'
 - mod 'puppetlabs-resource_api', '1.1.0'  (depricated)

I did try manually installing the `puppet-resource_api`, as suggested in https://github.com/puppetlabs/puppetlabs-resource_api/issues/36#issuecomment-737581921, but still had the error:
`/opt/puppetlabs/puppet/bin/gem install puppet-resource_api`

I know the `puppetlabs-resource_api` module was depricated back in March 2021, but I did not see any other options for using this module.  Should I manage UFW with a different module, or is there something I can do to fix this one?

**Comment by ZloeSabo** [comment]
Hey @dwest-galois,
I believe there is a problem either with your puppet environment or with the specific puppet version you use.

I've checked the test pipeline and acceptance tests [seem to be fine](https://github.com/kogitoapp/puppet-ufw/runs/6828432607?check_suite_focus=true). The ufw suite includes [creating a rule](https://github.com/kogitoapp/puppet-ufw/blob/main/spec/acceptance/ufw_spec.rb#L26) and it does not raise any exceptions.

In addition to that, we use the same module for our own infrastructure without any extra magic (afaik).

You also [don't need](https://github.com/puppetlabs/puppet-resource_api#deployment) to include the [puppetlabs-resource_api](https://forge.puppet.com/puppetlabs/resource_api) in your environment, if you're using puppet 6 or later as it is now a part of the puppet itself.

**Comment by ZloeSabo** [comment]
Now, when I think of it, a quite frequent source of mysterious puppet errors is wrong environment file permissions on the puppet master. Perhaps, that's the issue.

**Comment by ZloeSabo** [comment]
Closing this issue for now. Please reopen if needed.
